# Generated by Django 4.2 on 2023-04-24 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_identity_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Address title', max_length=250)),
                ('is_default', models.BooleanField(default=False)),
                ('country', models.CharField(default='Saudi Arabia', max_length=255)),
                ('full_name', models.CharField(default='first and last name', max_length=255)),
                ('mobile', models.CharField(default='00966', max_length=50)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(default='Eastern Province', max_length=255)),
                ('nearest_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
